import { Inter } from 'next/font/google'
import { NextDevtoolsProvider } from '@next-devtools/core'
import { type Metadata } from 'next'
import Header from '@/components/Header'
import './globals.css'
import "swagger-ui-react/swagger-ui.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextDevtoolsProvider>
          <Header/>
          {children}
        </NextDevtoolsProvider>
      </body>
    </html>
  )
}
